name: Output file, getting data from expression
on: [workflow_dispatch]
jobs: 
    githubRepoInfo: 
        runs-on: ubtuntu-latest
        steps:
            - name: Show Github keyword info
              run: echo "${{toJson(github)}}"